name: Linux-Installer-Builder Installer

on:
  - workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Install dependencies
      run: sudo apt install golang-go gcc libgtk-3-dev libglib2.0-dev make pkg-config zip

    - name: Build
      run: make self-installer

    - name: Upload
      uses: actions/upload-artifact@v2.2.2
      with:
        name: installer-builder.zip
        path: .release/linux-installer
